spring:
  profiles:
    active: ${profile}
    group:
      local: "local"
      dev: "dev, datasource"
    include:
        - security

  mvc:
    ignore-default-favicon: true

cors-allowed-origins:
  http://backya.duckdns.org:8080,
  http://localhost:8080,
  http://localhost:3000
