name: moplus-server
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy spring MainServer(develop)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd ~/Server
            git checkout master
            kill -9 $(lsof -t -i :8080)
            git add .
            git commit -m "temp commit"
            git fetch origin master
            git merge origin/master
            if [ $? -ne 0 ]; then
              echo "Merge conflict detected. Resolving by applying remote changes."
              git checkout --theirs $(git diff --name-only --diff-filter=U)
              git add .
              git commit -m "Resolved merge conflicts by applying remote changes."
            else
              echo "Merge successful, no conflicts detected."
            fi
            
            ./gradlew clean build
            docker rm -f backya-server-dev --force
            docker rmi backya-server-dev
            docker-compose -f docker-compose-dev.yml -p backya-server-dev up --build -d
